import type { Finding } from "./types";

export function buildIssueBody(findings: Finding[]): string {
  const fileList = findings
    .map(
      (f) => `* \`${f.filePath}:${f.line}\` (Confidence: **${f.confidence}**)`
    )
    .join("\n");

  return `
## 🚨 Potential Secrets Detected

Hello maintainers,

An automated scan has detected ${findings.length} potential secret(s) in this repository. We recommend reviewing them immediately.

### Findings

${fileList}

### Recommended Actions

1.  **Invalidate Keys:** Immediately rotate any keys or credentials that have been exposed.
2.  **Remove from History:** After invalidating, remove the secrets from your Git history. [GitHub has a guide for this](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository).
3.  **Secure Storage:** In the future, store secrets in a secure vault or use GitHub's encrypted secrets.

*This issue was generated by an automated tool and may contain false positives.*
  `;
}
